# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
    use_regexes: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    # evaluate_on_number_of_examples: 0
    # evaluate_every_number_of_epochs: 5
    # tensorboard_log_directory: "./tensorboard/DIET"
    # tensorboard_log_level: "epoch"
  - name: emotional_analysis.ea.SentimentAnalyzer
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 20
    epochs: 100
    constrain_similarities: true
    evaluate_on_number_of_examples: 0
    evaluate_every_number_of_epochs: 5
    tensorboard_log_directory: "./tensorboard/TED"
    tensorboard_log_level: "epoch"
  

